name: Publish Docker image
on:
  push:
    branches:
      - arm64v8

jobs:
  publish-docker-image:
    name: Publish Docker image
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: drupal10ci-arm64v8
          tags: arm64v8
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
